language: python
python:
  - "3.7"

services:
  - docker

before_script:
  - pip install -U pip
  - pip install pre-commit
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker create -it --name tmp lvconnolly/mychef_model:ingredient sh
  - docker cp tmp:/version ./api/app/services/models/ingredient
  - docker rm -f tmp
  - docker volume prune -f
  - docker-compose pull api
  - docker-compose up -d api

script:
  - pre-commit run --all-files
  - docker-compose exec api pytest tests
  - docker-compose down -v
