language: python
python:
  - "3.7"

services:
  - docker

before_script:
  - pip install -U pip && pip install pre-commit
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - ./scripts/download-models.sh
  - ./scripts/wipe-data.sh

script:
  - pre-commit run --all-files
  - docker-compose -f ./docker-compose.dev.yml exec api pytest tests
