version: '3.7'


services:

  api:
    build: ./api
    image: mychef_api:dev
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - ${API_PORT}:8000
    environment:
      - DATABASE_URL=${PG_DB_URL}

  scraper:
    build: ./scraper
    image: mychef_scraper:dev
    command: scrapyd-deploy scraper
    volumes:
      - ./scraper/:/usr/src/app/
    ports:
      - ${SCRAPER_PORT}:6023

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}

volumes:
  postgres_data:

