version: '3.7'

services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust

  search:
    image: getmeili/meilisearch:v0.16.0
    volumes:
      - ./backend/search/data.ms:/data.ms

  api:
    build: backend/api
    image: lvconnolly/mychef_api:dev
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    depends_on:
      - db
      - search

  proxy:
    build: proxy
    image: lvconnolly/mychef_proxy:dev
    restart: always
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - api
      - search

  scraper:
    build: backend/scraper
    image: lvconnolly/mychef_scraper:dev
    command: crawl full_helping
    depends_on:
      - api

volumes:
  postgres_data:
