version: '3.7'

services:
  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust

  search:
    image: getmeili/meilisearch:v0.16.0
    ports:
      - ${SEARCH_PORT}:7700
    volumes:
      - ./search/data.ms:/data.ms

  api:
    build: ./api
    image: lvconnolly/mychef_api:dev
    ports:
      - ${API_PORT}:8000
    volumes:
      - ./api/:/app
      - venv:/app/.venv
    environment:
      - API_INGREDIENT_MODEL=${API_INGREDIENT_MODEL}
      - WEB_PORT=${WEB_PORT}
      - WEB_HOST=${WEB_HOST}
      - SEARCH_PORT=${SEARCH_PORT}
      - SEARCH_HOST=${SEARCH_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - DEBUG_SERVER=true
    depends_on:
      - db
      - search

  proxy:
    build: proxy
    image: lvconnolly/mychef_proxy:dev
    restart: always
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - api
      - search

  scraper:
    build:
      context: scraper
    image: lvconnolly/mychef_scraper:dev
    environment:
      - INTERNAL_API_URL=${INTERNAL_API_URL}
    command: crawl full_helping
    depends_on:
      - api

volumes:
  postgres_data:
  venv:
