version: '3.7'


services:

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  scraper:
    build: ./scraper
    image: mychef_scraper:dev
    command: scrapyrt -p 6800 
    volumes:
      - ./scraper/:/usr/src/app/
    ports:
      - ${SCRAPER_PORT}:6800
    links:
      - "api:api"
        
  api:
    build: ./api
    image: mychef_api:dev
    ports:
      - ${API_PORT}:8000
    volumes:
      - ./api/:/app
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
    command: uvicorn src.main:app --reload --host 0.0.0.0
    depends_on:
      - db


volumes:
  postgres_data:
