version: '3.7'


services:

  api:
    build: ./api
    image: mychef_api:dev
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./api/:/usr/src/app/
    ports:
      - 8002:8000
